server:
  port: 8071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    
    username: root
    password: 1072
    
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    
      
    service-url:
      defaultZone: https://localhost:8761/eureka
      logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

    
     
      
    
    